### ISSUE TITLE
Rendering error on viewing a skin with ears.

### ISSUE THREAD

**Issue by DrPineap** [exaskye/Ears#11]
Game crashes whenever I try to view my skin. This is the report (let me know if you need more of it)
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 06/01/21 17:15
Description: Rendering entity in world

java.lang.NoSuchMethodError: com.mojang.blaze3d.matrix.MatrixStack$Entry.func_227870_a_()Lnet/minecraft/client/renderer/Matrix4f;
	at com.unascribed.ears.EarsLayerRenderer.renderFront(EarsLayerRenderer.java:131) ~[?:1.1.0] {re:mixin,re:classloading}
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:54) ~[?:1.1.0] {re:mixin,re:classloading}
	at com.unascribed.ears.EarsLayerRenderer.render(EarsLayerRenderer.java:56) ~[?:1.1.0] {re:mixin,re:classloading}
	at com.unascribed.ears.EarsLayerRenderer.func_225628_a_(EarsLayerRenderer.java:32) ~[?:1.1.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:204) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:obfuscate.mixins.json:client.OptifineLivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:ears.mixins.json:MixinPlayerRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:ears.mixins.json:MixinPlayerRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:310) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$15940/1453742288.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230450_a_(CreativeScreen.java:727) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:717) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.29.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/2097614581.call(Unknown Source) [forge-1.16.4-35.1.29.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.unascribed.ears.EarsLayerRenderer.renderFront(EarsLayerRenderer.java:131) ~[?:1.1.0] {re:mixin,re:classloading}
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:54) ~[?:1.1.0] {re:mixin,re:classloading}
	at com.unascribed.ears.EarsLayerRenderer.render(EarsLayerRenderer.java:56) ~[?:1.1.0] {re:mixin,re:classloading}
	at com.unascribed.ears.EarsLayerRenderer.func_225628_a_(EarsLayerRenderer.java:32) ~[?:1.1.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:204) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:obfuscate.mixins.json:client.OptifineLivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:ears.mixins.json:MixinPlayerRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:ears.mixins.json:MixinPlayerRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 431
	Entity Name: DrPineapple
	Entity's Exact location: 6744.50, 84.00, 12051.50
	Entity's Block location: World: (6744,84,12051), Chunk: (at 8,5,3 in 421,753; contains blocks 6736,0,12048 to 6751,255,12063), Region: (13,23; contains chunks 416,736 to 447,767, blocks 6656,0,11776 to 7167,255,12287)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.PlayerRenderer@3dbb78a0
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:310) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$15940/1453742288.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230450_a_(CreativeScreen.java:727) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:717) ~[?:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
	Mouse location: Scaled: (320, 331). Absolute: (641.000000, 663.000000)
	Screen size: Scaled: (479, 504). Absolute: (958, 1008). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['DrPineapple'/431, l='ClientLevel', x=6744.50, y=84.00, z=12051.50]]
	Chunk stats: Client Chunk Cache: 1225, 841
	Level dimension: minecraft:overworld
	Level spawn location: World: (6749,81,12053), Chunk: (at 13,5,5 in 421,753; contains blocks 6736,0,12048 to 6751,255,12063), Region: (13,23; contains chunks 416,736 to 447,767, blocks 6656,0,11776 to 7167,255,12287)
	Level time: 300 game time, 300 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.29.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/2097614581.call(Unknown Source) [forge-1.16.4-35.1.29.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

**Comment by exaskye** [comment]
Why did you close the issue?

This is weird; the "rotate" method on MatrixStack is missing...

**Comment by exaskye** [comment]
It would be good to see the complete game log rather than just part of the crash report. Please upload that as a file or put it on [Gist](https://gist.github.com).

**Comment by ColdIce1605** [comment]
@unascribed 
optifine?

**Comment by exaskye** [comment]
...If OptiFine is deleting methods from vanilla classes then I'm just going to stop supporting it.

**Comment by ColdIce1605** [comment]
I'm pretty sure it does that or something similar.

**Comment by exaskye** [comment]
I'm going to call this an OptiFine issue. Nothing I can do on my side as OptiFine is closed source, and if it is *disappearifying random vanilla methods* then there isn't really anything I can *try* to do either.
