### ISSUE TITLE
Forge 1.19.3

### ISSUE THREAD

**Issue by Zemogiter** [exaskye/Ears#110]
[latest.log](https://github.com/unascribed/Ears/files/10449241/latest.log)
Log snipped with the error:
```
[18sty2023 18:50:24.061] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:927) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1135) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:713) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.1.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.5.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/mojang/math/Matrix3f
	at com.unascribed.ears.EarsLayerRenderer$1.<init>(EarsLayerRenderer.java:152) ~[ears-forge-1.19-1.4.6.jar%23266!/:1.4.6]
	at com.unascribed.ears.EarsLayerRenderer.<init>(EarsLayerRenderer.java:78) ~[ears-forge-1.19-1.4.6.jar%23266!/:1.4.6]
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.handler$zeb000$init(PlayerRenderer.java:1531) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.<init>(PlayerRenderer.java:56) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174097_(EntityRenderers.java:24) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderers.m_234604_(EntityRenderers.java:170) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar%23100!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174051_(EntityRenderers.java:168) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_6213_(EntityRenderDispatcher.java:345) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1091) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.mojang.math.Matrix3f
	at com.unascribed.ears.EarsLayerRenderer$1.<init>(EarsLayerRenderer.java:152) ~[ears-forge-1.19-1.4.6.jar%23266!/:1.4.6]
	at com.unascribed.ears.EarsLayerRenderer.<init>(EarsLayerRenderer.java:78) ~[ears-forge-1.19-1.4.6.jar%23266!/:1.4.6]
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.handler$zeb000$init(PlayerRenderer.java:1531) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.<init>(PlayerRenderer.java:56) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174097_(EntityRenderers.java:24) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderers.m_234604_(EntityRenderers.java:170) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar%23100!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174051_(EntityRenderers.java:168) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_6213_(EntityRenderDispatcher.java:345) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1091) ~[client-1.19.3-20221207.122022-srg.jar%23316!/:?]
	... 16 more
```
Minecraft 1.19.3, ears 1.19-1.4.6, forge 44.1.5

**Comment by exaskye** [comment]
Ears does not yet support 1.19.3 on Forge.
