### ISSUE TITLE
Port Request: Fabric 1.19.4

### ISSUE THREAD

**Issue by TJT01** [exaskye/Ears#117]

**Comment by exaskye** [comment]
For my own reference:

```
java.lang.NoSuchFieldError: field_6211
	at com.unascribed.ears.EarsFeatureRenderer$1.getLimbSwing(EarsFeatureRenderer.java:362)
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:77)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:35)
	at com.unascribed.ears.EarsFeatureRenderer.renderRightArm(EarsFeatureRenderer.java:79)
	at net.minecraft.class_1007.handler$zza000$renderRightArm(class_1007.java:541)
	at net.minecraft.class_1007.method_4220(class_1007.java:179)
	at net.minecraft.class_759.method_3219(class_759.java:307)
```
