### ISSUE TITLE
1.4.5-1.7.10 Incompatibility with ArchaicFix on server

### ISSUE THREAD

**Issue by Gronglegrowth** [exaskye/Ears#139]
With ArchaicFix installed serverside (at least, I think that's the culprit here, educated guess), when players join said server with Ears on the client, Ears seems to fail at fetching skins for everyone except one's own, thus no one can see each others' skin. The log is spammed with the following error message when another player is in view:

`[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [com.unascribed.ears.legacy.LegacyHelper:getSkinUrl:152]: [Ears] Profile lookup failed
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.mcauthlib.util.HTTP.processResponse(HTTP.java:239)
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.mcauthlib.util.HTTP.performGetRequest(HTTP.java:199)
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.mcauthlib.util.HTTP.makeRequest(HTTP.java:91)
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.mcauthlib.util.HTTP.makeRequest(HTTP.java:108)
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.mcauthlib.service.SessionService.fillProfileProperties(SessionService.java:69)
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.LegacyHelper.getSkinUrl(LegacyHelper.java:140)
[14:15:47] [Ears lookup thread (655e263a-dd19-3e2b-940b-d032365ecdf7)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.unascribed.ears.legacy.LegacyHelper$2.run(LegacyHelper.java:93)`

Archaicfix is by default installed for clients too, but its presence clientside does not affect this, as I noted when joining another 1.7 server with Ears, which did not have that serverside.

If wanted/needed, I can provide more information such as the server's own modlist, a full client or server log, etc.

**Comment by exaskye** [comment]
This being caused by a server-side mod makes no sense. I've fixed the NPE cause but I suspect this was a transient Mojang API problem.
