### ISSUE TITLE
Crash with Just Expressions Resource Pack

### ISSUE THREAD

**Issue by SammyForReal** [exaskye/Ears#161]
#### Description

Having this mod installed with the [Entity Model Features](https://modrinth.com/mod/entity-model-features) mod by itself does not cause any issues. Then enabling the [Just Expressions Pack](https://modrinth.com/resourcepack/just-expressions) however **makes the client crash.**

#### More Context

In my case, the skin causing that issue is this one:
![58562dfd2e86d3da](https://github.com/unascribed/Ears/assets/53350357/dc6d7906-43d0-4e15-ba1f-2c7f0e23ddbe)

The skin is mainly prepared for the resource pack, though it also contains the data for the tail. Unfortunately, the ears texture place conflicts with the just expressions eyes, so the tail is the least that works with both enabled.

I am running this in Fabric _(mc1.21, though this affects multiple versions)_.

Interestingly enough, it does not crash with only having either Ears _or_ EMF or ETF installed with the skin. The crash only appears in this combination.

This crash seems to be kind of related with #155 in terms of the needed environment, but the crash is another one.

#### Steps to reproduce

1. Install the mods Ears, EMF and ETF
2. Prepare the skin 
3. Go into a SP world and toggle F5 to make the player skin visible.
4. Enable the Just Expressions Resource Pack
5. See crash.

#### Full Crash Report
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-06-27 16:03:28
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687)
	at net.minecraft.class_630.method_22700(class_630.java:180)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:100)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:84)
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.anchorTo(AbstractEarsRenderDelegate.java:106)
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:353)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:35)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:23)
	at com.unascribed.ears.EarsFeatureRenderer.render(EarsFeatureRenderer.java:73)
	at com.unascribed.ears.EarsFeatureRenderer.method_4199(EarsFeatureRenderer.java:60)
	at net.minecraft.class_922.method_4054(class_922.java:150)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687)
	at net.minecraft.class_630.method_22700(class_630.java:180)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:100)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:84)
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.anchorTo(AbstractEarsRenderDelegate.java:106)
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:353)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:35)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:23)
	at com.unascribed.ears.EarsFeatureRenderer.render(EarsFeatureRenderer.java:73)
	at com.unascribed.ears.EarsFeatureRenderer.method_4199(EarsFeatureRenderer.java:60)
	at net.minecraft.class_922.method_4054(class_922.java:150)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 91
	Entity Name: Sammy_craft
	Entity's Exact location: -3.57, 67.00, 124.64
	Entity's Block location: World: (-4,67,124), Section: (at 12,3,12 in -1,4,7; chunk contains blocks -16,-64,112 to -1,319,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@4d67989c
	Location: -1.85,-2.20,-3.50 - World: (-2,-3,-4), Section: (at 14,13,12 in -1,-1,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: -27.897646
	Delta: 0.28000283
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 28.915s
	Wall uptime: 23.533s
	High-res time: 23.262s
	Client ticks: 388 ticks / 19.400s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sammy_craft'/91, l='ClientLevel', x=-3.57, y=67.00, z=124.64]]
	Chunk stats: 961, 598
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,112), Section: (at 0,4,0 in 0,4,7; chunk contains blocks 0,-64,112 to 15,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1175 game time, 1175 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 180

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: vanilla, file/JustExpressions_v1.1.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.9.6-arch1-1
	Java Version: 21.0.3, JetBrains s.r.o.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), JetBrains s.r.o.
	Memory: 1063020960 bytes (1013 MiB) / 2218786816 bytes (2116 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: Comet Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU117 [GeForce GTX 1650]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MiB): 288.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 11994.55
	Virtual memory used (MiB): 9991.77
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 8.50
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 7849.69, total: 7898.55
	Space in storage for workdir (MiB): available: 74303.94, total: 113447.46
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.21
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.52.04, NVIDIA Corporation
	Window size: 1920x1011
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, file/JustExpressions_v1.1.zip
	Current Language: en_us
	Locale: en_DE
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sammy_craft'/91, l='ServerLevel[New World]', x=-3.57, y=67.00, z=124.64]]
	Active Data Packs: vanilla
	Available Data Packs: bundle, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -5511780394385996106
```

**Comment by ux92** [comment]
Can confirm, it's happening to us with Ears version 1.4.6 and Just Expressions 1.1.
It's not happening when disabling the resource pack itself. Not sure if it's tied to ETF/EMF.

**Comment by isdi0** [comment]
It appears to also happen with Fresh Moves. It must be any resource pack that attempts to modify the player model.

**Comment by k0nstruct** [comment]
Any resource pack that uses EMF on the player model crashes the game, apparently :(

**Comment by Russeki** [comment]
Updated a lot of mods and was panicking figuring out which mod was causing the crash. Didn't know a resourcepack incompatibility could crash my game.

**Comment by FuzziBearOfficial** [comment]
how to fix?

**Comment by exaskye** [comment]
Fixed in 2.0.0, which will be released soon™.
