### ISSUE TITLE
Crashes loading into multiplayer after launch

### ISSUE THREAD

**Issue by Cynosphere** [exaskye/Ears#75]
Going into singleplayer first prevents this.
```
java.lang.NullPointerException
	at bw.a(Render.java:41)
	at com_unascribed_ears_Ears$1.doBindSkin(com_unascribed_ears_Ears.java:141)
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.setUp(AbstractEarsRenderDelegate.java:48)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:61)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.DirectEarsRenderDelegate.render(DirectEarsRenderDelegate.java:18)
	at com_unascribed_ears_Ears.renderRightArm(com_unascribed_ears_Ears.java:111)
	at com_unascribed_ears_Ears.postDrawFirstPersonHand(com_unascribed_ears_Ears.java:37)
	at ds.drawFirstPersonHand(RenderPlayer.java:310)
	at ra.a(ItemRenderer.java:332)
	at px.b(EntityRenderer.java:434)
	at px.a(EntityRenderer.java:731)
	at px.b(EntityRenderer.java:505)
	at EntityRendererProxy.b(EntityRendererProxy.java:23)
	at net.minecraft.client.Minecraft.run(Minecraft.java:513)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by exaskye** [comment]
Ears is now integrated into NFC, and this bug has been fixed in the new native integration.
