### ISSUE TITLE
NSSS port is broken

### ISSUE THREAD

**Issue by Pete3R** [exaskye/Ears#87]
Geam no load
It works fine on _11 fine, however recent updates seem to have don' smth

 / Yes i did try without BTA photomode port (essentially fresh NSSS) and same crash

Here's crashlog, or i hope at least: whatever MultiMC has given me at least

```
MultiMC version: 0.7.0-develop-3452


Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.199.41, 52.84.199.46, 52.84.199.53, 52.84.199.60]

session.minecraft.net resolves to:
    [54.164.34.185, 54.173.66.187, 52.7.153.255]

textures.minecraft.net resolves to:
    [54.192.231.84, 54.192.231.107, 54.192.231.87, 54.192.231.57]

api.mojang.com resolves to:
    [54.192.231.100, 54.192.231.23, 54.192.231.114, 54.192.231.107]


Minecraft folder is:
/media/gamedisk/Minecraft Instances MultiMC/NSSS_a1.1.11_111/.minecraft


Java path is:
/usr/lib64/jvm/java-8-openjdk/jre/bin/java


Checking Java version...
Java is version 1.8.0_332, using 64-bit architecture, from Oracle Corporation.


Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd Device 4013

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 515.48.07

Main Class:
  com.mojang.minecraft.Minecraft

Native path:
  /media/gamedisk/Minecraft Instances MultiMC/NSSS_a1.1.11_111/natives

Traits:
traits no-texturepacks

Libraries:
  /home/pete/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/pete/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/pete/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar
  /home/pete/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar
  /media/gamedisk/Minecraft Instances MultiMC/NSSS_a1.1.11_111/.minecraft/bin/minecraft.jar

Native libraries:
  /home/pete/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/pete/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-linux.jar

Jar Mods:
  a1.1.11_111 (a1.1.11_111.jar)
  bta_photomode_nsss_a1.1.11_111_v0.1 (42072e4b-050b-4e4e-9898-b75f09362719.jar)

Params:
     --gameDir /media/gamedisk/Minecraft Instances MultiMC/NSSS_a1.1.11_111/.minecraft --assetsDir /home/pete/.local/share/multimc/assets

Window size: 854 x 480

Java Arguments:
[-javaagent:ears.jar, -Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xms1024m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 267382


Hello from Ears v1.4.5 for Not So Seecret Saturday!
Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.Error: java.lang.NoSuchFieldException: field_209_f
	at com.unascribed.ears.Ears.<clinit>(Ears.java:302)
	at com.mojang.minecraft.render.TexturedQuad.<init>(TexturedQuad.java:26)
	at com.mojang.minecraft.entity.model.ModelRenderer.addBox(ModelRenderer.java:81)
	at com.mojang.minecraft.entity.model.ModelBiped.<init>(ModelBiped.java:28)
	at com.mojang.minecraft.entity.model.ModelBiped.<init>(ModelBiped.java:19)
	at com.mojang.minecraft.Minecraft.<init>(Minecraft.java:171)
	at com.mojang.minecraft.MinecraftImpl.<init>(MinecraftImpl.java:18)
	at com.mojang.minecraft.Minecraft.startMainThread(Minecraft.java:1711)
	at com.mojang.minecraft.Minecraft.start(Minecraft.java:1696)
	at com.mojang.minecraft.Minecraft.main(Minecraft.java:1755)
	... 8 more
Caused by: java.lang.NoSuchFieldException: field_209_f
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.unascribed.ears.Ears.<clinit>(Ears.java:293)
	... 17 more
Exiting with -1
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

**Comment by exaskye** [comment]
All Ears retrofork ports are broken right now due to changes in the retroforks they target; I haven't gotten around to updating them yet.
