### ISSUE TITLE
[3D Shareware (pre-1.14 April Fools)] Crashes on World Load

### ISSUE THREAD

**Issue by Flexico** [exaskye/Ears#90]
Yes, I tried different versions of Java, and got the same crash! It does not crash with only Fabric, but does crash with only Fabric and Ears.

============================

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.46.48, 65.8.46.45, 65.8.46.62, 65.8.46.49]

session.minecraft.net resolves to:
    [54.173.66.187, 54.164.34.185, 52.7.153.255]

textures.minecraft.net resolves to:
    [52.85.247.19, 52.85.247.36, 52.85.247.121, 52.85.247.86]

api.mojang.com resolves to:
    [13.249.85.70, 13.249.85.55, 13.249.85.48, 13.249.85.108]

Minecraft folder is:
D:/Minecraft/MultiMC/instances/Vanilla - Shareware/.minecraft

Java path is:
D:/Minecraft/MultiMC/java/jdk-17-windows/bin/javaw.exe

Checking Java version...
Java is version 17, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  D:/Minecraft/MultiMC/instances/Vanilla - Shareware/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  D:/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/datafixerupper/2.0.23/datafixerupper-2.0.23.jar
  D:/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  D:/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/realms/1.14.2/realms-1.14.2.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.2/text2speech-1.11.2.jar
  D:/Minecraft/MultiMC/libraries/net/fabricmc/intermediary/3D Shareware v1.34/intermediary-3D Shareware v1.34.jar
  D:/Minecraft/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  D:/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  D:/Minecraft/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  D:/Minecraft/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  D:/Minecraft/MultiMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  D:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  D:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  D:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  D:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  D:/Minecraft/MultiMC/libraries/net/fabricmc/fabric-loader/0.14.8/fabric-loader-0.14.8.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/minecraft/3D Shareware v1.34/minecraft-3D Shareware v1.34-client.jar

Native libraries:
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-windows.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-windows.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-windows.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1-natives-windows.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-windows.jar
  D:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-windows.jar
  D:/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.2/text2speech-1.11.2-natives-windows.jar

Mods:
  [✔️] ears-fabric-1.14-1.4.5

Params:
  --username  --version 3D Shareware v1.34 --gameDir D:/Minecraft/MultiMC/instances/Vanilla - Shareware/.minecraft --assetsDir D:/Minecraft/MultiMC/assets --assetIndex 1.14-af --uuid  --accessToken  --userType  --versionType snapshot

Window size: 1024 x 768

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 15732

Using onesix launcher.

[13:26:22] [main/INFO]: Loading Minecraft 3D Shareware v1.34 with Fabric Loader 0.14.8
[13:26:22] [main/INFO]: Loading 4 mods:
	- ears 1.4.5
	- fabricloader 0.14.8
	- java 17
	- minecraft 1.14-alpha.19.13.shareware
[13:26:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:26:23] [Client thread/INFO]: Setting user: Flexico64
[13:26:27] [Client thread/WARN]: Skipping bad option: lastServer:
[13:26:27] [Client thread/WARN]: Skipping bad option: enableVsync:true
[13:26:27] [Client thread/WARN]: Skipping bad option: fullscreen:false
[13:26:27] [Client thread/WARN]: Skipping bad option: maxFps:60
[13:26:27] [Client thread/WARN]: Skipping bad option: forceUnicodeFont:false
[13:26:27] [Client thread/INFO]: LWJGL Version: 3.2.1 build 12
[13:26:30] [Client thread/INFO]: Narrator library for x64 successfully loaded
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:block.bell.resonate
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:entity.evoker.celebrate
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:entity.ravager.celebrate
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:entity.pillager.celebrate
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:entity.villager.celebrate
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:entity.vindicator.celebrate
[13:26:36] [Client thread/WARN]: Missing sound for event: minecraft:entity.witch.celebrate
[13:26:36] [Client thread/INFO]: OpenAL initialized.
[13:26:36] [Client thread/INFO]: Sound engine started
[13:26:36] [Client thread/INFO]: Created: 1024x512 textures-atlas
[13:26:36] [Client thread/WARN]: Could not find uniform named Resolution in the specified shader program.
[13:26:36] [Client thread/WARN]: Could not find uniform named MosaicSize in the specified shader program.
[13:26:36] [Client thread/INFO]: Created: 256x256 textures/particle-atlas
[13:26:36] [Client thread/INFO]: Created: 256x256 textures/painting-atlas
[13:26:36] [Client thread/INFO]: Created: 256x128 textures/mob_effect-atlas
[13:27:05] [Client thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:27:05] [Client thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:27:05] [Client thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:27:05] [Client thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:27:05] [Client thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:27:05] [Server thread/INFO]: Starting integrated minecraft server version 3D Shareware v1.34
[13:27:05] [Server thread/INFO]: Generating keypair
[13:27:05] [Server thread/INFO]: Reloading ResourceManager: Default
[13:27:05] [Server thread/INFO]: Loaded 6 recipes
[13:27:06] [Server thread/INFO]: Loaded 809 advancements
[13:27:06] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:27:07] [Client thread/INFO]: Preparing spawn area: 0%
[13:27:07] [Client thread/INFO]: Preparing spawn area: 0%
[13:27:07] [Client thread/INFO]: Preparing spawn area: 0%
[13:27:08] [Client thread/INFO]: Preparing spawn area: 0%
[13:27:08] [Client thread/INFO]: Preparing spawn area: 4%
[13:27:09] [Client thread/INFO]: Preparing spawn area: 8%
[13:27:09] [Client thread/INFO]: Preparing spawn area: 16%
[13:27:10] [Client thread/INFO]: Preparing spawn area: 29%
[13:27:10] [Client thread/INFO]: Preparing spawn area: 43%
[13:27:11] [Client thread/INFO]: Preparing spawn area: 61%
[13:27:11] [Client thread/INFO]: Preparing spawn area: 100%
[13:27:12] [Client thread/INFO]: Time elapsed: 5513 ms
[13:27:12] [Server thread/INFO]: Flexico64[local:E:95c43245] logged in with entity id 158 at (-322.29004892966714, 64.0, -264.4708886091842)
[13:27:12] [Server thread/INFO]: Flexico64 joined the game
[13:27:13] [Server thread/INFO]: Saving and pausing game...
[13:27:13] [Server thread/INFO]: Saving chunks for level 'MoJang Presents'/minecraft:overworld
[13:27:13] [Client thread/INFO]: Loaded 124 advancements
[13:27:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (shareware): All chunks are saved
[13:27:14] [Server thread/INFO]: Saving chunks for level 'MoJang Presents'/minecraft:the_nether
[13:27:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:27:14] [Server thread/INFO]: Saving chunks for level 'MoJang Presents'/minecraft:the_end
[13:27:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:27:14] [Server thread/INFO]: Stopping server
[13:27:14] [Server thread/INFO]: Saving players
[13:27:14] [Server thread/INFO]: Flexico64 lost connection: Disconnected
[13:27:14] [Server thread/INFO]: Flexico64 left the game
[13:27:14] [Server thread/INFO]: Stopping singleplayer server as player logged out
[13:27:14] [Server thread/INFO]: Saving worlds
[13:27:14] [Server thread/INFO]: Saving chunks for level 'MoJang Presents'/minecraft:overworld
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (shareware): All chunks are saved
[13:27:15] [Server thread/INFO]: Saving chunks for level 'MoJang Presents'/minecraft:the_nether
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:27:15] [Server thread/INFO]: Saving chunks for level 'MoJang Presents'/minecraft:the_end
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (shareware): All chunks are saved
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (shareware): All chunks are saved
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:27:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:27:15] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_2486(class_490.java:142) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1759(class_329.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:674) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:973) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:425) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_742.method_20231()'
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:95) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:66) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.anchorTo(AbstractEarsRenderDelegate.java:106) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:154) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.common.render.DirectEarsRenderDelegate.render(DirectEarsRenderDelegate.java:18) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.EarsFeatureRenderer.render(EarsFeatureRenderer.java:48) ~[ears-fabric-1.14-1.4.5.jar:?]
	at com.unascribed.ears.EarsFeatureRenderer.method_4199(EarsFeatureRenderer.java:37) ~[ears-fabric-1.14-1.4.5.jar:?]
	at net.minecraft.class_922.method_4051(class_922.java:444) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:385) ~[client-intermediary.jar:?]
	... 18 more
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/23/22, 1:27 PM
Description: Rendering entity in world

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_742.method_20231()'
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:95)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:66)
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.anchorTo(AbstractEarsRenderDelegate.java:106)
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:154)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.DirectEarsRenderDelegate.render(DirectEarsRenderDelegate.java:18)
	at com.unascribed.ears.EarsFeatureRenderer.render(EarsFeatureRenderer.java:48)
	at com.unascribed.ears.EarsFeatureRenderer.method_4199(EarsFeatureRenderer.java:37)
	at net.minecraft.class_922.method_4051(class_922.java:444)
	at net.minecraft.class_922.method_4054(class_922.java:166)
	at net.minecraft.class_1007.method_4215(class_1007.java:69)
	at net.minecraft.class_1007.method_3936(class_1007.java:35)
	at net.minecraft.class_898.method_3954(class_898.java:385)
	at net.minecraft.class_490.method_2486(class_490.java:142)
	at net.minecraft.class_329.method_1759(class_329.java:529)
	at net.minecraft.class_329.method_1753(class_329.java:183)
	at net.minecraft.class_757.method_3192(class_757.java:674)
	at net.minecraft.class_310.method_1523(class_310.java:973)
	at net.minecraft.class_310.method_1514(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:95)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:66)
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.anchorTo(AbstractEarsRenderDelegate.java:106)
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:154)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.DirectEarsRenderDelegate.render(DirectEarsRenderDelegate.java:18)
	at com.unascribed.ears.EarsFeatureRenderer.render(EarsFeatureRenderer.java:48)
	at com.unascribed.ears.EarsFeatureRenderer.method_4199(EarsFeatureRenderer.java:37)
	at net.minecraft.class_922.method_4051(class_922.java:444)
	at net.minecraft.class_922.method_4054(class_922.java:166)
	at net.minecraft.class_1007.method_4215(class_1007.java:69)
	at net.minecraft.class_1007.method_3936(class_1007.java:35)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 158
	Entity Name: Flexico64
	Entity's Exact location: -322.29, 64.00, -264.47
	Entity's Block location: World: (-323,64,-265), Chunk: (at 13,4,7 in -21,-17; contains blocks -336,0,-272 to -321,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_1297.toString()" because the return value of "net.minecraft.class_1297.method_5854()" is null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@6b8cfbeb
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:385)
	at net.minecraft.class_490.method_2486(class_490.java:142)
	at net.minecraft.class_329.method_1759(class_329.java:529)
	at net.minecraft.class_329.method_1753(class_329.java:183)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [class_746['Flexico64'/158, l='MpServer', x=-322.29, y=64.00, z=-264.47]]
	Chunk stats: MultiplayerChunkCache: 729, 234
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-192,63,-200), Chunk: (at 0,3,8 in -12,-13; contains blocks -192,0,-208 to -177,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 27071 game time, 27071 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:447)
	at net.minecraft.class_310.method_1587(class_310.java:1968)
	at net.minecraft.class_310.method_1514(class_310.java:433)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 3D Shareware v1.34
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 423354448 bytes (403 MB) / 1233125376 bytes (1176 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	Launched Version: 3D Shareware v1.34
	LWJGL: 3.2.1 build 12
	OpenGL: NVIDIA GeForce MX250/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.40, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
#@!@# Game crashed! Crash report saved to: #@!@# D:\Minecraft\MultiMC\instances\Vanilla - Shareware\.minecraft\crash-reports\crash-2022-06-23_13.27.15-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

**Comment by exaskye** [comment]
The missing method is `isInSneakingPose`. What?

**Comment by Flexico** [comment]
Wait, where did you see that? I searched the log and don't see that phrase.

**Comment by exaskye** [comment]
`method_20231` is `isInSneakingPose` in Yarn.
